<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CaseInfo extends Model
{
    protected $table = 'case_information';

    protected $fillable = [
        'company_id',
        'order_id',
        'fever_above_38',
        'sore_throat',
        'runny_nose',
        'cough',
        'shortness_of_breath',
        'vomitting',
        'diarrhoea',
        'other_samples_taken',
        'icu_required',
        'ards',
        'pneumonia_xray',
        'severe_infection',
        'ventilation_required',
        'ecm_oxygenation',
        'domestic_travel',
        'domestic_travel_start',
        'domestic_travel_end',
        'domestic_region_visited',
        'domestic_cities_visited',
        'international_travel',
        'international_travel_start',
        'international_travel_end',
        'countries_visited',
        'cities_visited',
        'positive_case_contact',
        'attended_mass_gatherings',
        'location_of_exposure',
        'inpatient_admission',
        'traditional_healer',
        'occupation',
        'form_completed',
        'data_collector_info',
        'name_of_data_collector',
        'data_collector_institution',
        'form_completion_date',
        'respondent_name',
        'respondent_sex',
        'respondent_dob',
        'respondent_age',
        'respondent_email',
        'respondent_address',
        'respondent_phone',
        'case_studies',
        'respondent_name2',
        'respondent_sex2',
        'respondent_dob2',
        'respondent_address2',
        'respondent_phone2',
        'respondent_relationship',
        'date_of_first_symptom',
        'date_respiratory_sample_collected',
        'respiratory_sample',
        'sample_type',
        'sample_date',
        'hospital',
        'hospital_name',
        'employment_location',
        'incomplete_form_reason',
    ];
}
